export const APP_CHILD_DEFAULT_WIDTH = 600;

export const APP_CHILD_DEFAULT_HEIGHT = 400;

export const APP_CHILD_DEFAULT_POSITION_X = 200;

export const APP_CHILD_DEFAULT_POSITION_Y = 100;

export const APP_CHILD = {
  APP_CHILD_DEFAULT_WIDTH,
  APP_CHILD_DEFAULT_HEIGHT,
  APP_CHILD_DEFAULT_POSITION_X,
  APP_CHILD_DEFAULT_POSITION_Y,
};
