export const APP_NAME = "raccoon-widget";

export const APP_CONFIG_FILE_NAME = "config.txt";

export const APP_LOG_FILE_NAME = "log.txt";

export const APP_STORAGE_FILE_NAME = "storage.txt";

export const APP_DEFAULT_WIDTH = 800;

export const APP_DEFAULT_HEIGHT = 600;

export const APP_DEFAULT_POSITION_X = 100;

export const APP_DEFAULT_POSITION_Y = 100;

export const APP_CHILD_DEFAULT_WIDTH = 600;

export const APP_CHILD_DEFAULT_HEIGHT = 400;

export const APP_CHILD_DEFAULT_POSITION_X = 200;

export const APP_CHILD_DEFAULT_POSITION_Y = 100;

export const APP = {
  APP_NAME,
  APP_CONFIG_FILE_NAME,
  APP_LOG_FILE_NAME,
  APP_STORAGE_FILE_NAME,
  APP_DEFAULT_WIDTH,
  APP_DEFAULT_HEIGHT,
  APP_DEFAULT_POSITION_X,
  APP_DEFAULT_POSITION_Y,
};

export const APP_CHILD = {
  APP_CHILD_DEFAULT_WIDTH,
  APP_CHILD_DEFAULT_HEIGHT,
  APP_CHILD_DEFAULT_POSITION_X,
  APP_CHILD_DEFAULT_POSITION_Y,
};
