/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BluetoothLazyImport = createFileRoute('/bluetooth')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const BluetoothLazyRoute = BluetoothLazyImport.update({
  id: '/bluetooth',
  path: '/bluetooth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bluetooth.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/bluetooth': {
      id: '/bluetooth'
      path: '/bluetooth'
      fullPath: '/bluetooth'
      preLoaderRoute: typeof BluetoothLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/bluetooth': typeof BluetoothLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/bluetooth': typeof BluetoothLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/bluetooth': typeof BluetoothLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bluetooth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bluetooth'
  id: '__root__' | '/' | '/bluetooth'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BluetoothLazyRoute: typeof BluetoothLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BluetoothLazyRoute: BluetoothLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bluetooth"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/bluetooth": {
      "filePath": "bluetooth.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
